version: '3.8'

services:
  debian:
    image: debian
    container_name: my-debian
    tty: true
    stdin_open: true

    ports:
      - '11111:5244'
      - '11122:22'

    command:
      - /bin/bash
      - -c
      - |
        apt update && \
        apt install -y wget && \
        wget -O setup.sh https://raw.githubusercontent.com/lonelysoul/immortalwrt/refs/heads/main/docker_setup.sh && \
        chmod +x setup.sh && \
        ./setup.sh
