name: Mine

on:
  push:
    branches:
      - main  # 修改为你的默认分支

jobs:
  check_update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config user.email "actions@github.com"
        git config user.name "GitHub Actions"
        
    - name: Fetch upstream changes
      run: |
        git remote add upstream https://github.com/openwrt/openwrt.git
        git fetch upstream

    - name: Check for changes and modify file if needed
      run: |
        git status
        git log -n 5 --pretty=format:"%h - %an, %ar : %s"
        CHANGES=$(git rev-list HEAD...upstream/main --count)
        echo "Number of changes: $CHANGES"
        
        if [ "$CHANGES" -gt 0 ]; then
          echo "There are changes in the upstream repository."
          # 在这里添加修改本地文件的命令，例如修改一个文件的内容
          # 例如，将文件中的某个字符串替换为指定内容
          sed -i 's/old_content/new_content/' resault.txt
          git add resault.txt
          git commit -m "Update file due to upstream changes"
          git push origin main  # 将修改推送回你的仓库
        else
          echo "No changes in the upstream repository."
        fi
