#
# 版权所有（c）2019-2021 P3TERX <https://p3terx.com>
#
# 这是一款免费软件，根据 MIT 许可证授权。
# 更多信息请查看 /LICENSE 文件。
#
# https://github.com/P3TERX/Actions-OpenWrt
# 文件: .github/workflows/update-checker.yml
# 描述: 源代码更新检查
#

name: Immortalwrt更新检查
env:
  REPO_URL: https://github.com/immortalwrt/immortalwrt
  REPO_BRANCH: master

on:
  # 手动触发工作流程
  workflow_dispatch:
  # 定时触发，每18小时执行一次
  schedule:
    - cron: 0 */18 * * *

jobs:
  check:
    runs-on: ubuntu-latest

    steps:

    - name: 获取提交哈希值
      id: getHash
      run: |
        git clone --depth 1 $REPO_URL -b $REPO_BRANCH .
        echo "commitHash=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
        # 如果需要输出到输出变量，可以使用下面的语句
        # echo "::set-output name=commitHash::$(git rev-parse HEAD)"

    - name: 比较提交哈希值
      id: cacheHash
      uses: actions/cache@v3
      with:
        path: .commitHash
        key: HEAD-${{ steps.getHash.outputs.commitHash }}
        
    - name: 保存新的提交哈希值
      if: steps.cacheHash.outputs.cache-hit != 'true'
      run: |
        echo ${{ steps.getHash.outputs.commitHash }} | tee .commitHash

    - name: 触发构建
      if: steps.cacheHash.outputs.cache-hit != 'true'
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ secrets.ACTIONS_TRIGGER_PAT }}
        event-type: Immortalwrt源码更新触发release自动编译
        
    - name: 删除工作流运行
      uses: Mattraks/delete-workflow-runs@v2.0.6
      with:
        token: ${{ secrets.ACTIONS_TRIGGER_PAT }}
        repository: ${{ github.repository }}
        retain_days: 1
        keep_minimum_runs: 3
